#  http://localhost:585/login/oauth2/code/google
#  http://localhost:585/oauth2/authorization/google
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 850654767182-ur5db52cs3a1q4phv6l3qee97nq5skud.apps.googleusercontent.com
            client-secret: 0WKx9xIpCzkQejcB_G_K3jXE
          facebook:
            client-id: your-app-client-id
            client-secret: your-app-client-secret
          okta:
            client-id: your-app-client-id
            client-secret: your-app-client-secret
        provider:
          okta:
            authorization-uri: https://your-subdomain.oktapreview.com/oauth2/v1/authorize
            token-uri: https://your-subdomain.oktapreview.com/oauth2/v1/token
            user-info-uri: https://your-subdomain.oktapreview.com/oauth2/v1/userinfo
            jwk-set-uri: https://your-subdomain.oktapreview.com/oauth2/v1/keys

#https://docs.spring.io/spring-security/site/docs/current/reference/html5/#oauth2login-boot-property-mappings:
