server:
  port: 585
  forward-headers-strategy: native

logging.pattern.dateformat: yyyy-MM-dd HH:mm:ss.SSS,Europe/Moscow

spring:
  application:
    name: oauth2
  profiles:
    include:
      - oauth2
  datasource:
    username: auth
    password: auth-password
    url: jdbc:postgresql://localhost:5432/colaba
  jpa:
    properties.hibernate:
      default_schema: auth
    hibernate.ddl-auto: validate
  main.allow-bean-definition-overriding: true
  jackson:
    default-property-inclusion: non_empty
    time-zone: GMT+3
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false
  boot.admin.client:
    url: http://localhost:8090
    username: admin
    password: admin
eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka

management:
  endpoints.web.exposure.include: '*'
  endpoint.health.show-details: ALWAYS

---
spring:
  profiles: production
  cloud.config.uri: http://config-server:8888
  boot.admin.client.url: http://admin-server:8090
  datasource.url: jdbc:postgresql://postgres:5432/colaba
eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka
